sender: add some missing request-response pairs to the send sync method
Added:
   * Transmit request (0x10), Explicit addressing command request (0x11):
     Extended transmit status (0x8B)
   * 64-bit transmit request (0x00), 16-bit transmit request (0x01), User data
     relay input (0x2D) (1): Transmit status (0x89)
   * File system request (0x3B): File system response (0xBB)
   * Remote file system request (0x3C): Remote file system response (0xBC) (2)
   * Register joining device (0x24): Register joining device status (0xA4)

(1): User data relay input requests (0x2D) only receive a transmit status frame
     (0x89) for errors. This means successful user data relay input requests
     throw a TimeoutException using this method.
(2): A remote file system request (0x3C) may receive 2 frames: the remote file
     system response (0xBC) and a transmit status (0x8B) only for errors (there
     is already an issue opened to change this behavior: XBHAWK-530)

This changes also try to avoid exception (appeared only once):

Exception in thread Thread-3:
Traceback (most recent call last):
  File ".../python3.6/threading.py", line 916, in _bootstrap_inner
  File ".../python3.6/site-packages/digi/xnm/bridge.py", line 1405, in run
  File ".../python3.6/site-packages/digi/xnm/bridge.py", line 1441, in _init_remote_node
  File ".../python3.6/site-packages/digi/xnm/bridge.py", line 3177, in add_route_for_node
  File ".../python3.6/site-packages/digi/xbee/devices.py", line 4162, in get_route_to_node
  File ".../python3.6/site-packages/digi/xbee/devices.py", line 4265, in __get_trace_route
AttributeError: 'RemoteATCommandResponsePacket' object has no attribute 'transmit_status'

Signed-off-by: Tatiana Leon <Tatiana.Leon@digi.com>