firmware: ota: s2c: fix check of updater hardware version
When updating a remote S2C XBee the following exception is thrown since the
updater node is already discovered and its trying to access to item 0 of the
integer of its hardware version.

exception calling callback for <Future at 0xb55d0690 state=finished raised TypeError>
Traceback (most recent call last):
  File ".../python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
  File ".../python3.6/site-packages/digi/xbee/reader.py", line 91, in __execution_finished
  File ".../python3.6/concurrent/futures/thread.py", line 56, in run
  File ".../python3.6/site-packages/digi/xnm/bridge.py", line 561, in packet_from_end_device_cb
  File ".../python3.6/site-packages/digi/xnm/bridge.py", line 695, in __update_node
  File ".../python3.6/site-packages/digi/xbee/devices.py", line 1876, in apply_profile
  File ".../python3.6/site-packages/digi/xbee/profile.py", line 1967, in apply_xbee_profile
  File ".../python3.6/site-packages/digi/xbee/profile.py", line 1867, in update_profile
  File ".../python3.6/site-packages/digi/xbee/profile.py", line 1489, in _update_firmware
  File ".../python3.6/site-packages/digi/xbee/devices.py", line 1814, in update_firmware
  File ".../python3.6/site-packages/digi/xbee/firmware.py", line 5558, in update_remote_firmware
  File ".../python3.6/site-packages/digi/xbee/firmware.py", line 1644, in update_firmware
  File ".../python3.6/site-packages/digi/xbee/firmware.py", line 2298, in _configure_updater
  File ".../python3.6/site-packages/digi/xbee/firmware.py", line 4748, in _configure_updater_extra
  File ".../python3.6/site-packages/digi/xbee/firmware.py", line 4830, in _determine_updater_device_zigbee
TypeError: 'int' object is not subscriptable

Signed-off-by: Tatiana Leon <Tatiana.Leon@digi.com>