devices: zigbee: update node parent if updater and new info node are Zigbee
This fix the following exception when updating a local XBee to a different
firmware protocol. For example, if updating from a Zigbee firmware to a DigiMesh
firmware:

Traceback (most recent call last):
   File "/data/dal/romfs/usr/lib/python3.6/site-packages/digi/xbee/reader.py", line 602, in run
   File "/data/dal/romfs/usr/lib/python3.6/site-packages/digi/xbee/reader.py", line 1638, in __try_add_remote_device
   File "/data/dal/romfs/usr/lib/python3.6/site-packages/digi/xbee/devices.py", line 9767, in _add_remote_from_attr
   File "/data/dal/romfs/usr/lib/python3.6/site-packages/digi/xbee/devices.py", line 9714, in _add_remote
   File "/data/dal/romfs/usr/lib/python3.6/site-packages/digi/xbee/devices.py", line 246, in update_device_data_from AttributeError: 'RemoteDigiMeshDevice' object has no attribute 'parent

Signed-off-by: Tatiana Leon <Tatiana.Leon@digi.com>