profile: configure default timeout if not specified when applying profile
Keeping 'None' as timeout as default value triggers an exception when closing
the XBee.

Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/media/tleon/data/git/xbee-mqtt/digi/xnm/bridge.py", line 307, in run
    self.__update_routers_coordinator(router_coord_tasks)
  File "/media/tleon/data/git/xbee-mqtt/digi/xnm/bridge.py", line 432, in __update_routers_coordinator
    self.__update_node(self.__active)
  File "/media/tleon/data/git/xbee-mqtt/digi/xnm/bridge.py", line 647, in __update_node
    progress_callback=self.__update_progress_cb)
  File "/media/tleon/data/git/xbee-mqtt/venv/lib/python3.6/site-packages/digi/xbee/devices.py", line 1610, in apply_profile
    profile.apply_xbee_profile(self, profile_path, timeout=timeout, progress_callback=progress_callback)
  File "/media/tleon/data/git/xbee-mqtt/venv/lib/python3.6/site-packages/digi/xbee/profile.py", line 1492, in apply_xbee_profile
    profile_updater.update_profile()
  File "/media/tleon/data/git/xbee-mqtt/venv/lib/python3.6/site-packages/digi/xbee/profile.py", line 1443, in update_profile
    self._update_device_settings()
  File "/media/tleon/data/git/xbee-mqtt/venv/lib/python3.6/site-packages/digi/xbee/profile.py", line 1343, in _update_device_settings
    self._check_port_settings_changed()
  File "/media/tleon/data/git/xbee-mqtt/venv/lib/python3.6/site-packages/digi/xbee/profile.py", line 1246, in _check_port_settings_changed
    self._xbee_device.close()  # This is necessary to stop the frames read thread.
  File "/media/tleon/data/git/xbee-mqtt/venv/lib/python3.6/site-packages/digi/xbee/devices.py", line 2379, in close
    self._packet_listener.stop()
  File "/media/tleon/data/git/xbee-mqtt/venv/lib/python3.6/site-packages/digi/xbee/reader.py", line 603, in stop
    self.__comm_iface.quit_reading()
  File "/media/tleon/data/git/xbee-mqtt/venv/lib/python3.6/site-packages/digi/xbee/serial.py", line 200, in quit_reading
    time.sleep(self.timeout)
TypeError: an integer is required (got type NoneType)

Signed-off-by: Tatiana Leon <tatiana.leon@digi.com>